[package]
name = "recallgate-lock-wayland"
description = "Recall Gate Wayland session lock client"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish = false

[features]
default = []
ui = ["dep:glib", "dep:gtk4", "dep:gtk4-session-lock"]

[[bin]]
name = "recallgate-lock-wayland"
path = "src/main.rs"
required-features = ["ui"]

[lib]
path = "src/lib.rs"

[dependencies]
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
glib = { version = "0.20.9", optional = true }
gtk4 = { version = "=0.10.3", optional = true }
gtk4-session-lock = { version = "=0.3.0", optional = true }

[lints]
workspace = true
